# Generated by Django 4.0 on 2022-01-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20220114_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
